services:
  api:
    container_name: LibreChat
    ports:
      - "${PORT}:${PORT}"
    image: ghcr.io/danny-avila/librechat-dev:latest
    restart: always
    user: "${UID}:${GID}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - HOST=0.0.0.0
      - MONGO_URI=mongodb://atlas:27017/LibreChat
      - NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt
    volumes:
      - type: bind
        source: ./librechat.yaml
        target: /app/librechat.yaml
      - /etc/ssl/certs:/etc/ssl/certs
    depends_on:
      - atlas
    env_file:
      - .env
    networks:
      - librechat-net
  rag_api:
    container_name: rag_api
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
    environment:
      - DB_HOST=atlas
      - VECTOR_DB_TYPE=atlas-mongo
      - ATLAS_MONGO_DB_URI=mongodb://atlas:27017/LibreChat
      - ATLAS_SEARCH_INDEX=vectorindex
      - COLLECTION_NAME=ragcollection
      - RAG_PORT=${RAG_PORT:-8000}
      - SSL_CERT_FILE=/app/paychex-root.pem
      - REQUESTS_CA_BUNDLE=/app/paychex-root.pem
      - CURL_CA_BUNDLE=/app/paychex-root.pem
    restart: always
    depends_on: 
      - atlas
    volumes:
      - type: bind
        source: ./paychex-root.pem
        target: /app/paychex-root.pem
      - /etc/ssl/certs:/etc/ssl/certs
    networks:
      - librechat-net 
  mongodb:
    image: rjocoleman/noop:latest
    environment:
      - NOOP_INFINITY=true
    command: "sleep infinity"
  vectordb:
    image: rjocoleman/noop:latest
    command: "sleep infinity"
    environment:
      - NOOP_INFINITY=true
    volumes: [] #Clearing volumes since its we are not using PostGres
  # atlas:
  #   hostname: atlas
  #   restart: unless-stopped
  #   image: mongodb/mongodb-atlas-local
  #   ports:
  #     - 27017:27017
  #   # volumes:
  #   #   - ./configdb:/data/configdb
  #   volumes:
  #     - ./config-db:/data/configdb
  #     - ./data:/data/db
        #- MONGODB_ATLAS_ACCEPT_EULA=yes
  atlas:
    image: busybox
    command: ["sh", "-c", "sleep infinity"]
    restart: no
networks:
  librechat-net:
    external: true

# volumes:
#   data:
#   config-db: