name: N1 - Build and Push

env:
  # Azure ACR
  ACR_HOST: ${{ vars.REGISTRY_LOGIN_SERVER_NONPROD }}
  ACR_USER: ${{ secrets.REGISTRY_USERNAME_NONPROD }}
  ACR_PASS: ${{ secrets.REGISTRY_PASSWORD_NONPROD }}

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_HOST }}
          username: ${{ env.ACR_USER }}
          password: ${{ env.ACR_PASS }}

      - name: Build and push docker container
        run: |
          docker build . -t ${{ env.ACR_HOST }}/paychex/librechat:n1.${{ github.sha }}
          docker push ${{ env.ACR_HOST }}/paychex/librechat:n1.${{ github.sha }}

          docker build . -t ${{ env.ACR_HOST }}/paychex/librechat:n1.latest
          docker push ${{ env.ACR_HOST }}/paychex/librechat:n1.latest

      - name: Update Azure Container App
        run: |
          az login --identity
          az containerapp update \
            --name conpaichateastusn1001 \
            --resource-group rg-playai-eastus-n1-001 \
            --yaml ./n1_container_app_definition.yml
