name: prod - Build and Push

env:
    # Azure ACR
    ACR_HOST: ${{ vars.REGISTRY_LOGIN_SERVER_PROD }}
    ACR_USER: ${{ secrets.REGISTRY_USERNAME_PROD }}
    ACR_PASS: ${{ secrets.REGISTRY_PASSWORD_PROD }}

on:
  workflow_dispatch:

jobs:
    build_and_push:
        runs-on: paychex-ai-platform-arc-prod
        steps:
            - uses: actions/checkout@v3

            - name: Create Config File
              run: |
                touch librechat.yaml && chmod 755 librechat.yaml |
                cat librechat.prod.yaml >> librechat.yaml |
                rm -rf .dockerignore |
                touch .dockerignore && chmod 755 .dockerignore |
                cat .paychex.dockerignore >> .dockerignore |
                cat .dockerignore

            - name: log in to ACR
              uses: azure/docker-login@v1
              with:
                login-server: ${{ env.ACR_HOST }}
                username: ${{ env.ACR_USER }}
                password: ${{ env.ACR_PASS }}


            - name: Azure CLI script
              uses: azure/cli@v2
              with:
                  inlineScript: |
                    az login --service-principal -u ${{secrets.ARC_RUNNER_SP_CLIENT_ID_PROD}} -p ${{secrets.ARC_RUNNER_SP_CLIENT_SECRET_PROD}} --tenant ${{secrets.AZURE_TENANT_ID}}
                    az account set --subscription "${{ secrets.AZURE_PROD_SUBSCRIPTION_ID }}"
                    az containerapp create \
                      --name conpaichateastusprod001 \
                      --resource-group rg-playai-eastus-prod-001 \
                      --yaml $GITHUB_WORKSPACE/az_container_app_definitions/prod_container_app_definition.yml
                
