name: N2A - Build and Push

env:
    # Azure ACR
    ACR_HOST: ${{ vars.REGISTRY_LOGIN_SERVER_PROD }}
    ACR_USER: ${{ secrets.REGISTRY_USERNAME_PROD }}
    ACR_PASS: ${{ secrets.REGISTRY_PASSWORD_PROD }}
    AZURE_CONFIG_DIR: ${{ github.workspace }}/.azure-cli-tmp

on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - main

jobs:
    build_and_push:
        runs-on: [self-hosted, nonprod]
        steps:
            - uses: actions/checkout@v3

            - name: Create Config File
              run: |
                touch librechat.yaml && chmod 755 librechat.yaml |
                cat librechat.prod.yaml >> librechat.yaml |
                rm -rf .dockerignore |
                touch .dockerignore && chmod 755 .dockerignore |
                cat .paychex.dockerignore >> .dockerignore |
                cat .dockerignore

            - name: Prepare Azure CLI config dir
              run: mkdir -p "$AZURE_CONFIG_DIR"

            - name: log in to ACR
              uses: azure/docker-login@v1
              with:
                login-server: ${{ env.ACR_HOST }}
                username: ${{ env.ACR_USER }}
                password: ${{ env.ACR_PASS }}

            - name: build and push docker container
              run: |
                docker build . -t ${{ env.ACR_HOST }}/paychex/librechat:prod.${{ github.sha }}
                docker push ${{ env.ACR_HOST }}/paychex/librechat:prod.${{ github.sha }}

                docker build . -t ${{ env.ACR_HOST }}/paychex/librechat:prod.latest
                docker push ${{ env.ACR_HOST }}/paychex/librechat:prod.latest

            - name: Update Azure Container App
              run: |
                az login --identity
                az account set --subscription "${{ secrets.AZURE_PROD_SUBSCRIPTION_ID }}"
                az containerapp update \
                  --name conpaichateastusprod001 \
                  --resource-group rg-playai-eastus-prod-001 \
                  --yaml $GITHUB_WORKSPACE/az_container_app_definitions/prod_container_app_definition.yml
                
